[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "foo_parameterization"
version = "0.1.0"
authors = [{name = "Evan De la Garza"}]
description = "A Python package to calculate the Foo parameterization."
readme = "README.md"